valkey:
  auth:
    enabled: true
    sentinel: false
    existingSecret: argo-cd-cache-secret
    # That's the key wanted by argo-cd.
    existingSecretPasswordKey: redis-password
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
    podMonitor:
      enabled: true