postgresql:
  global:
    postgresql:
      auth:
        username: harbor
        existingSecret: harbor-db-secret
        postgresPassword: postgres
        secretKeys:
          adminPasswordKey: postgres-password
          userPasswordKey: password

  tls:
    enabled: true
    certificatesSecret: harbor-db-tls-secret

  primary:
    initdb:
      scripts:
        # See: https://github.com/goharbor/harbor/blob/main/make/photon/db/initial-registry.sql
        initial-registry.sql: |-
          CREATE DATABASE registry ENCODING 'UTF8';
          \c registry;

          CREATE TABLE schema_migrations(version bigint not null primary key, dirty boolean not null);

    persistence:
      size: 10Gi

    resourcesPreset: "small"

  # Warning: go-harbordb is still using 15 (and 14).
  # See: https://github.com/goharbor/harbor/blob/main/make/photon/db/Dockerfile.base
  image:
    # https://hub.docker.com/r/bitnami/postgresql
    registry: docker.io
    repository: bitnami/postgresql
    tag: 15.8.0

certificate:
  enabled: true

  secretName: harbor-db-tls-secret # same as above

  issuerRef:
    name: private-ca-cluster-issuer
    kind: ClusterIssuer
